#!/bin/sh

echo "[+] config mysql"
mysql_install_db --user=root --datadir=/var/lib/mysql
run_mysql(){
    mysqld_safe --defaults-file=/etc/my.cnf --user=root --character-set-server=utf8 &
}
mysql_ready() {
    mysqladmin ping --socket=/etc/mysql/mysql.sock --user=root > /dev/null 2>&1
}

if [ -f "/flag.sh" ];then
  echo "[+] config before service start"
  source /flag.sh
fi

export FLAG=not_here
FLAG=not_here

echo "[+] start default services"
while !(mysql_ready)
do
    echo "[i] waiting for mysql ..."
    mysql_ready
    if [ $? -ne 0 ]; then
        run_mysql
    fi
    sleep 3
done
php-fpm &
nginx

echo "[+] init mysql"
mysql -uroot -proot -e "DROP DATABASE IF EXISTS test;DELETE FROM mysql.user WHERE user='';"
mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;FLUSH PRIVILEGES;"

tail -f /dev/null