#!/bin/sh

echo "[+] config mysql"
mysql_install_db --user=root --datadir=/var/lib/mysql
run_mysql(){
    mysqld_safe --defaults-file=/etc/my.cnf --user=root --character-set-server=utf8 &
}
mysql_ready() {
    mysqladmin ping --socket=/etc/mysql/mysql.sock --user=root > /dev/null 2>&1
}

if [ -f "/flag.sh" ];then
  echo "[+] config before service start"
  source /flag.sh
fi

export FLAG=not_here
FLAG=not_here

echo "[+] start default services"
while !(mysql_ready)
do
    echo "[i] waiting for mysql ..."
    mysql_ready
    if [ $? -ne 0 ]; then
        run_mysql
    fi
    sleep 3
done
php-fpm &
nginx

if [ -f "/tmp/initdb.sql" ];then
  echo "[+] init mysql"
  mysql -uroot -proot -e "SOURCE /tmp/initdb.sql;"
  rm /tmp/initdb.sql
fi

tail -f /dev/null